# Site settings
title: 'Samuel Arnesen'
description: "Software Engineer at Amazon"
url: ''
#baseurl: '/jekyll-uno-remote-theme-demo'
baseurl: ''


remote_theme: matthiaslischka/jekyll-uno

author:
  name: 'Samuel Arnesen'
  email: 'samuel.p.arnesen@gmail.com'
  #twitter_username: 
  #facebook_username: 
  github_username: samuelarnesen
  linkedin_username:  samuelarnesen

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
future: true
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache
  
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', '.travis.yml', 'vendor']